"""PDF and JSON export (Phase 7.1)."""

from __future__ import annotations

import json
from io import BytesIO
from typing import Any

from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle


def _safe_str(v: Any, default: str = "") -> str:
    if v is None:
        return default
    if isinstance(v, str):
        return v
    return str(v)


def _threat_color(level: str) -> colors.Color:
    lv = (level or "").lower()
    if lv in ("critical", "high"):
        return colors.HexColor("#ff3860")
    if lv == "medium":
        return colors.HexColor("#ffb800")
    if lv == "low":
        return colors.HexColor("#00ff88")
    return colors.HexColor("#6b7a99")


def generate_pdf(analysis_result: dict[str, Any]) -> bytes:
    """Multi-page forensic PDF per PRD §7.1."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=letter,
        rightMargin=54,
        leftMargin=54,
        topMargin=54,
        bottomMargin=54,
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "DSTFATitle",
        parent=styles["Heading1"],
        fontSize=22,
        textColor=colors.HexColor("#00d4ff"),
        spaceAfter=12,
    )
    h2 = ParagraphStyle("H2", parent=styles["Heading2"], fontSize=14, spaceBefore=14, spaceAfter=8)
    body = ParagraphStyle("Body", parent=styles["Normal"], fontSize=9, leading=12)
    small = ParagraphStyle("Small", parent=styles["Normal"], fontSize=8, textColor=colors.grey)

    story: list[Any] = []
    aid = _safe_str(analysis_result.get("analysis_id"))
    ts = _safe_str(analysis_result.get("timestamp"))
    summary = analysis_result.get("input_summary") or {}
    subject = _safe_str(summary.get("subject"))
    from_addr = _safe_str(summary.get("from"))
    llm = analysis_result.get("llm_insights") or {}
    threat = _safe_str(llm.get("threat_level"), "unknown")

    def footer(canvas: Any, doc_: Any) -> None:
        canvas.saveState()
        canvas.setFont("Helvetica", 8)
        canvas.setFillColor(colors.grey)
        footer_text = f"Page {doc_.page} — Generated by DSTFA v2.0"
        canvas.drawString(54, 36, footer_text)
        canvas.restoreState()

    # Page 1 — Cover
    story.append(Paragraph("DSTFA Forensic Report", title_style))
    story.append(Paragraph(f"<b>Analysis time (UTC):</b> {ts}", body))
    story.append(Spacer(1, 0.2 * inch))
    story.append(
        Table(
            [[Paragraph("<b>Threat level</b>", body), Paragraph(threat.upper(), body)]],
            colWidths=[1.4 * inch, 3 * inch],
            style=TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, -1), _threat_color(threat)),
                    ("TEXTCOLOR", (0, 0), (-1, -1), colors.white),
                    ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#1e2d4a")),
                    ("LEFTPADDING", (0, 0), (-1, -1), 8),
                    ("RIGHTPADDING", (0, 0), (-1, -1), 8),
                    ("TOPPADDING", (0, 0), (-1, -1), 8),
                    ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
                ]
            ),
        )
    )
    story.append(Spacer(1, 0.25 * inch))
    story.append(Paragraph(f"<b>Subject:</b> {subject}", body))
    story.append(Paragraph(f"<b>From:</b> {from_addr}", body))
    story.append(Spacer(1, 0.35 * inch))
    story.append(Paragraph(f"<b>Analysis ID:</b> {aid}", small))

    # Page 2 — Authentication
    story.append(Paragraph("Authentication results", h2))
    auth = analysis_result.get("authentication") or {}

    def auth_row(protocol: str, block: dict[str, Any]) -> list[str]:
        if not isinstance(block, dict):
            return [protocol, "—", "—", "—"]
        return [
            protocol,
            _safe_str(block.get("result"), "none").upper(),
            _safe_str(block.get("domain") or block.get("ip")),
            _safe_str(block.get("explanation"))[:500],
        ]

    auth_data = [
        ["Protocol", "Result", "Domain / IP", "Explanation"],
        auth_row("SPF", auth.get("spf") or {}),
        auth_row("DKIM", auth.get("dkim") or {}),
        auth_row("DMARC", auth.get("dmarc") or {}),
        auth_row("ARC", auth.get("arc") or {}),
    ]
    t_auth = Table(auth_data, colWidths=[0.9 * inch, 0.85 * inch, 1.25 * inch, 3.5 * inch])
    t_auth.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2340")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#1e2d4a")),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )
    story.append(t_auth)

    # Page 3 — Hashes
    story.append(Paragraph("Hash analysis", h2))
    hashes = analysis_result.get("hashes") or {}
    body_h = hashes.get("body") or {}
    hash_rows = [
        ["Field", "Value"],
        ["Body SHA-256", _safe_str(body_h.get("sha256"))],
        ["Body MD5", _safe_str(body_h.get("md5"))],
        ["Body SHA-1", _safe_str(body_h.get("sha1"))],
    ]
    t_hash = Table(hash_rows, colWidths=[1.4 * inch, 5.1 * inch])
    t_hash.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2340")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#1e2d4a")),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("FONTNAME", (1, 1), (1, -1), "Courier"),
            ]
        )
    )
    story.append(t_hash)
    md = hashes.get("merkle_damgard_steps") or {}
    if isinstance(md, dict):
        algo = _safe_str(md.get("algorithm"), "SHA-256")
        blocks = md.get("blocks") or []
        nblocks = len(blocks) if isinstance(blocks, list) else 0
        flags = hashes.get("vulnerability_flags") or {}
        weak = _safe_str(flags.get("weak_hash_explanation")) if isinstance(flags, dict) else ""
        story.append(Spacer(1, 0.12 * inch))
        story.append(
            Paragraph(
                f"<b>Merkle–Damgård ({algo}):</b> {nblocks} compression block(s). "
                f"{'MD5-related weakness noted.' if (isinstance(flags, dict) and flags.get('md5_detected')) else ''}",
                body,
            )
        )
        if weak:
            story.append(Paragraph(weak[:800], small))

    # Page 4 — Digital signatures
    story.append(Paragraph("Digital signatures", h2))
    sigs = analysis_result.get("digital_signatures") or {}
    pgp = sigs.get("pgp") or {}
    sm = sigs.get("smime") or {}
    sig_tbl = Table(
        [
            ["", "PGP", "S/MIME"],
            ["Present", str(pgp.get("present")), str(sm.get("present"))],
            ["Valid", str(pgp.get("valid")), str(sm.get("valid"))],
            ["Key / subject", _safe_str(pgp.get("key_id"))[:40], _safe_str(sm.get("subject_cn"))[:40]],
            ["Algorithm", _safe_str(pgp.get("algorithm")), _safe_str(sm.get("algorithm"))],
        ],
        colWidths=[1.2 * inch, 2.6 * inch, 2.6 * inch],
    )
    sig_tbl.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2340")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 0.25, colors.HexColor("#1e2d4a")),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(sig_tbl)

    # Page 5 — LLM summary
    story.append(Paragraph("LLM forensic summary", h2))
    if isinstance(llm, dict) and llm:
        story.append(Paragraph(_safe_str(llm.get("forensic_summary"))[:3500], body))
        findings = llm.get("key_findings") or []
        if isinstance(findings, list) and findings:
            story.append(Spacer(1, 0.1 * inch))
            story.append(Paragraph("<b>Key findings</b>", body))
            for i, f in enumerate(findings[:25], start=1):
                story.append(Paragraph(f"{i}. {_safe_str(f)}", body))
    else:
        story.append(Paragraph("No LLM insights were generated for this analysis.", body))

    # Page 6 — Entities
    story.append(Paragraph("Entity extraction", h2))
    entities = llm.get("entity_extraction") if isinstance(llm, dict) else {}
    if isinstance(entities, dict) and entities:
        for label, key in (("IPs", "ips"), ("Domains", "domains"), ("URLs", "urls"), ("IoCs", "iocs")):
            vals = entities.get(key)
            if not isinstance(vals, list):
                vals = entities.get(key.upper(), [])
            if not isinstance(vals, list):
                continue
            rows = [[label]] + [[_safe_str(x)[:120]] for x in vals[:40]]
            if len(rows) == 1:
                continue
            et = Table(rows, colWidths=[6.5 * inch])
            et.setStyle(
                TableStyle(
                    [
                        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2340")),
                        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                        ("GRID", (0, 0), (-1, -1), 0.2, colors.HexColor("#1e2d4a")),
                        ("FONTSIZE", (0, 0), (-1, -1), 8),
                    ]
                )
            )
            story.append(et)
            story.append(Spacer(1, 0.08 * inch))
    else:
        story.append(Paragraph("No structured entities in LLM output.", small))

    # Page 7 — Timeline
    story.append(Paragraph("Timeline reconstruction", h2))
    timeline = llm.get("timeline_reconstruction") if isinstance(llm, dict) else []
    if isinstance(timeline, list) and timeline:
        trows: list[list[str]] = [["Time / ref", "Description", "Source"]]
        for ev in timeline[:40]:
            if not isinstance(ev, dict):
                continue
            trows.append(
                [
                    _safe_str(ev.get("timestamp") or ev.get("time")),
                    _safe_str(ev.get("description") or ev.get("event"))[:200],
                    _safe_str(ev.get("source")),
                ]
            )
        tt = Table(trows, colWidths=[1.35 * inch, 3.85 * inch, 1.3 * inch])
        tt.setStyle(
            TableStyle(
                [
                    ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a2340")),
                    ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                    ("GRID", (0, 0), (-1, -1), 0.2, colors.HexColor("#1e2d4a")),
                    ("FONTSIZE", (0, 0), (-1, -1), 7),
                    ("VALIGN", (0, 0), (-1, -1), "TOP"),
                ]
            )
        )
        story.append(tt)
    else:
        story.append(Paragraph("No timeline entries.", small))

    # Page 8 — Chain of custody
    story.append(Paragraph("Chain of custody", h2))
    coc = llm.get("chain_of_custody_log") if isinstance(llm, dict) else {}
    if isinstance(coc, dict) and coc:
        for k in sorted(coc.keys()):
            story.append(Paragraph(f"<b>{k}:</b> {_safe_str(coc.get(k))}", small))
    else:
        story.append(Paragraph("No chain-of-custody log (LLM not run or omitted).", small))

    doc.build(story, onFirstPage=footer, onLaterPages=footer)
    pdf = buf.getvalue()
    buf.close()
    return pdf


def generate_json_export(analysis_result: dict[str, Any]) -> str:
    return json.dumps(analysis_result, indent=2, default=str)
